[package]
name = "backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
actix-web = "4.0.0"
actix-rt = "2.5"
dotenv = "0.15"
sqlx = { version = "0.6", features = ["runtime-actix-native-tls", "mysql"] }
serde = "1.0"
serde_derive = "1.0"
env_logger = "0.10"